---

cluster_name: "{{ lookup('env', 'CLUSTER_NAME')}}"
cluster_type: "{{ lookup('env', 'CLUSTER_TYPE')}}"

# For already provisioned clusters set token and server to log directly into rather than cluster type (ROKS/Fyre) specific login
ocp_token: "{{ lookup('env', 'OCP_TOKEN') }}"
ocp_server: "{{ lookup('env', 'OCP_SERVER') }}"

# IBM Cloud ROKS API Key - used when cluster_type == "roks"
ibmcloud_apikey: "{{ lookup('env', 'IBMCLOUD_APIKEY') }}"

# Fyre username/password - used when cluster_type == "quickburn"
username: "{{ lookup('env', 'FYRE_USERNAME') }}"
password: "{{ lookup('env', 'FYRE_APIKEY') }}"

# What cluster types does this role support
supported_cluster_types:
  - roks
  - quickburn
  - in-cluster
  - aws

k8s_auth_host: "{{ lookup('env', 'K8S_AUTH_HOST') | default('', True) }}"
