---
kafka_namespace: "{{ lookup('env', 'KAFKA_NAMESPACE') | default('amq-streams', true) }}"
kafka_cluster_name: "{{ lookup('env', 'KAFKA_CLUSTER_NAME') | default('maskafka', true)  }}"
kafka_cluster_size: "{{ lookup('env', 'KAFKA_CLUSTER_SIZE') | default('small', true)  }}"
kafka_storage_class: "{{ lookup('env', 'KAFKA_STORAGE_CLASS') }}"
kafka_user_name: "{{ lookup('env', 'KAFKA_USER_NAME') | default('masuser', true)  }}"

# When these variables are defined we will create the KafkaCfg resource, if either is missing then the configuration will not be generated
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"
