---
# Default application spec for HPUtilities
mas_app_ws_spec:
  bindings:
    watsonstudio: system
  components: {}
  settings:
    watsonstudio:
      projectid: dummy-value # need hpu team to tell if this can be set to a default value
