---
# 1. Fyre Login
# -----------------------------------------------------------------------------
- name: "login-quickburn : Fail if username is not provided"
  assert:
    that: username is defined and username != ""
    fail_msg: "username property is required"

- name: "login-quickburn : Fail if password is not provided"
  assert:
    that: password is defined and password != ""
    fail_msg: "password property is required"

- name: "login-quickburn : Get Cluster Details"
  uri:
    url: https://ocpapi.svl.ibm.com/v1/ocp/{{ cluster_name }}
    user: "{{ username }}"
    password: "{{ password }}"
    method: GET
    force_basic_auth: yes
    validate_certs: false
  register: _cluster_details

- set_fact:
    api_host: "api.{{ cluster_name }}.cp.fyre.ibm.com"
    _this_cluster: "{{ _cluster_details.json.clusters | selectattr('cluster_name', '==', cluster_name) | last }}"

- name: "login-quickburn : Oc Login the created cluster"
  vars:
    login_password: "{{ _this_cluster.kubeadmin_password }}"
    login_server: "https://{{ api_host }}:6443"
  shell: |
    oc login -u kubeadmin -p {{ login_password }} --server={{ login_server }} --insecure-skip-tls-verify=true
