---

mas_catalog_source: "{{ lookup('env', 'MAS_CATALOG_SOURCE') | default('ibm-operator-catalog', true) }}"
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_namespace: "mas-{{ mas_instance_id }}-core"

mas_upgrade_supported_channels: ['8.6.x']

# Set this to target channel for the 8.7 release when available
# When using pre-release development catalog source, this can be set to m3dev87
mas_upgrade_target_channel: 8.7.x

mas_app_upgrade_supported_channels:
  assist: []
  hputilities: ['8.2.x']
  iot: ['8.4.x']
  manage: ['8.2.x']
  monitor: ['8.6.x']
  predict: ['8.4.x']
  safety: ['8.2.x']
  visualinspection: []

# Set these to target channels for the 8.7 releases when available
# When using pre-release development catalog sources, these can be set to any 8.7 development channel
mas_app_upgrade_target_channels:
  assist:
  hputilities: 8.3.x
  iot: 8.4.x
  manage: 8.3.x
  monitor: 8.7.x
  predict: 8.5.x
  safety: 8.2.x
  visualinspection:

common_services_namespace: ibm-common-services

# default_custom_cluster_issuer: "cis-letsencrypt-production-{{ mas_instance_id }}"
# custom_cluster_issuer: "{{ lookup('env', 'MAS_CUSTOM_CLUSTER_ISSUER') | default(default_custom_cluster_issuer, true), lookup('env', 'MAS_CUSTOM_CLUSTER_ISSUER') | default(None, true) }}"

cert_names:
  # CA for signing all the individual certs for internal use
  internal_ca: "{{ mas_instance_id }}-cert-internal-ca"
  # public certs
  public: "{{ mas_instance_id }}-cert-public"
  public_ca: "{{ mas_instance_id }}-cert-public-ca"

internal_certificate_issuer:
  name: "{{ mas_namespace }}-internal-issuer"

internal_ca_issuer:
  name: "{{ mas_namespace }}-internal-ca-issuer"
