---
# MAS instance configuration
db2_schema: "{{ lookup('env', 'MAS_DB2_SCHEMA') | default('maximo', true)}}"

mas_appws_components: "{{ lookup('env', 'MAS_APPWS_COMPONENTS') | ibm.mas_devops.appws_components | default(omit, true) }}"
