---

# 1. Setup namespaces for OCS
# -----------------------------------------------------------------------------
- name: "ocs/storage : Create Namespaces for OCS"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/storage/namespace.yaml') }}"
  register: localNamespace


# 2. Install the Operator
# -----------------------------------------------------------------------------
- name: "ocs/storage : Create Openshift Container Storage Operator Group"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/storage/operatorgroup.yaml') }}"
  register: ocsGroup

- name: "ocs/storage : Openshift Container Storage Operator Subscription"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/storage/subscription.yaml') }}"
  register: ocsSubscription

# 3. Wait until the StorageCluster CRD is available
# -----------------------------------------------------------------------------
- name: "Wait until the StorageCluster CRD is available"
  kubernetes.core.k8s_info:
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: "storageclusters.ocs.openshift.io"
    wait: yes
    wait_sleep: 10
    wait_timeout: 300 # 5 mins until we give up waiting for the CRD to get into the expected state
    wait_condition:
      type: NamesAccepted
      status: "True"
  register: storagecluster_crd_info
  retries: 120 # ~approx 5 minutes before we give up waiting for the CRD to be created
  delay: 5 # seconds
  until:
    - storagecluster_crd_info.resources is defined
    - storagecluster_crd_info.resources | length > 0


# 4. Create the storage cluster
# -----------------------------------------------------------------------------
- name: "ocs/storage : Create OSC Cluster"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/storage/storagecluster.yaml') }}"


# 4. Provide debug information
# -----------------------------------------------------------------------------
- name: "ocs/storage : Debug information"
  debug:
    msg:
      - "OperatorGroup changed ........ {{ ocsGroup.changed }}"
      - "Subscription changed ......... {{ ocsSubscription.changed }}"
