---

# 1. Install IBM catalogs
# -----------------------------------------------------------------------------
# In an airgap install scenario, the catalogs are already installed as part of
# preparing the cluster
- name: "Create IBM catalogs"
  when:
    - not airgap_install
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'templates/ibm-catalogs.yml') }}"


# 2. Install development (pre-release) catalogs
# -----------------------------------------------------------------------------
# In an airgap install scenario, the catalogs are already installed as part of
# preparing the cluster
- name: "Install development (pre-release) catalogs"
  when:
    - artifactory_username is defined and artifactory_username != ""
    - artifactory_apikey is defined and artifactory_apikey != ""
    - not airgap_install
  include_tasks: "tasks/development-catalogs.yml"
