---

# 1. Wait for CP4D service CR to be ready
# -----------------------------------------------------------------------------
# Unfortunately CP4D do not have a standard approach to managing status across
# their services like MAS does, so we need module-specific wait code.

- name: "wait-spark : Wait for analyticsengineStatus 'Completed' or 'Failed'"
  kubernetes.core.k8s_info:
    api_version: "{{ cpd_service_info[cpd_service_name].api_version }}"
    kind: "{{ cpd_service_info[cpd_service_name].crd_kind }}"
    name: "{{ cpd_service_info[cpd_service_name].cr_name }}"
    namespace: "{{ cpd_instance_namespace }}"
  register: cpd_cr_lookup
  until:
    - cpd_cr_lookup.resources is defined
    - cpd_cr_lookup.resources | length == 1
    - cpd_cr_lookup.resources[0].status is defined
    - cpd_cr_lookup.resources[0].status.analyticsengineStatus is defined
    - cpd_cr_lookup.resources[0].status.analyticsengineStatus == "Completed" or cpd_cr_lookup.resources[0].status.analyticsengineStatus == "Failed"
  retries: 30 # Up to 1 hour
  delay: 120 # Every 2 minutes

- name: "wait-spark : Check that the WML analyticsengineStatus is 'Completed'"
  assert:
    that: cpd_cr_lookup.resources[0].status.analyticsengineStatus == "Completed"
    fail_msg: "Analytics Engine (Apache Spark) install failed (analyticsengineStatus)"
