---
- hosts: localhost
  any_errors_fatal: true

# 1. Deploy & configure the cluster
# -----------------------------------------------------------------------------
- name: Deploy ROKS cluster in IBM Cloud
  import_playbook: ocp/provision-roks.yml

- name: Login & configure OCP cluster
  import_playbook: ocp/configure-ocp.yml
  vars:
    cluster_type: roks
    prometheus_storage_class: ibmc-block-gold
    prometheus_alertmgr_storage_class: ibmc-file-gold-gid


# 2. Default Cluster Secret Hack for CP4D
# -----------------------------------------------------------------------------
# Note: We will perform this hack even when installing cp4d v3, for which it's
# not technically necessary, but it does not harm other than adding some time to
# the overall playbook run.  The extra complexity of deciding when to run this
# is not worth the overhead for this sample end-to-end playbook.
#
# We hope to find out how to avoid doing this entirely in the new year, as it
# shouldn't be a requirement to restart worker nodes and modify the default image
# pull secret to use any containerized software.
- name: Update default cluster pull secret and reboot all worker nodes
  import_playbook: cp4d/hack-worker-nodes.yml
  vars:
    cluster_type: roks


# 3. Install MongoDb
# -----------------------------------------------------------------------------
- name: Install MongoDb (Community Edition)
  import_playbook: dependencies/install-mongodb-ce.yml
  vars:
    mongodb_storage_class: ibmc-block-gold


# 4. Install Db2 CP4D service
# -----------------------------------------------------------------------------
- name: Install CP4D services
  import_playbook: cp4d/install-services-db2.yml
  vars:
    mas_channel: "{{ lookup('env', 'MAS_CHANNEL') | default('8.x', True) }}" #  when defined, it will automatically install a cpd version that is compatible with the chosen mas_channel
    cpd_storage_class: ibmc-file-gold-gid


# 5. Install SLS
# -----------------------------------------------------------------------------
- name: Install SLS
  import_playbook: dependencies/install-sls.yml
  vars:
    sls_storage_class: ibmc-file-gold-gid
    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"

    # Use the generated mongodb configuration
    mongodb_namespace: "{{ lookup('env', 'MONGODB_NAMESPACE') | default('mongoce', True) }}"
    sls_mongodb_cfg_file: "{{ mas_config_dir }}/mongo-{{ mongodb_namespace }}.yml"


# 6. Install UDS
# -----------------------------------------------------------------------------
- name: Install UDS
  import_playbook: dependencies/install-uds.yml
  vars:
    uds_storage_class: "ibmc-block-bronze"


# 7. Create DB2 Warehouse instance in CP4D
# -----------------------------------------------------------------------------
- name: Install CP4D services & configure Db2
  import_playbook: cp4d/create-db2-instance.yml
  vars:
    db2wh_instance_name: db2w-shared
    db2wh_meta_storage_class: ibmc-file-silver-gid
    db2wh_user_storage_class: ibmc-file-gold-gid
    db2wh_backup_storage_class: ibmc-file-gold-gid
    db2wh_logs_storage_class: ibmc-file-silver-gid # only applicable for cp4d 4.0
    db2wh_temp_storage_class: ibmc-file-silver-gid # only applicable for cp4d 4.0
    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"

# Temporary hack for Manage, because the operator is missing critical
# database configuration that requires manual intervention to set up.
- name: Db2 configuration hack for Manage
  import_playbook: mas/hack-manage-db2.yml
  vars:
    db2wh_instance_name: db2w-shared


# 8. Generate a Workspace
# -----------------------------------------------------------------------------
- name: Generate Workspace Configuration
  import_playbook: mas/gencfg-workspace.yml
  vars:
    # Note: If you change the ID of the workspace, make sure to also update it
    # in subsequent roles as well
    mas_workspace_name: "MAS Development"
    mas_workspace_id: masdev


# 9. Install & configure MAS
# -----------------------------------------------------------------------------
- name: Install & configure MAS
  import_playbook: mas/install-suite.yml
  vars:
    mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"


# 10. Install & Configure Manage application
# -----------------------------------------------------------------------------
# Tip, to install the Health application in standalone mode, simply change
# mas_app_id to "health" in the following tasks, nothing else needs to be changed

- name: Install Manage
  import_playbook: mas/install-app.yml
  vars:
    mas_app_id: manage
- name: Configure Manage
  import_playbook: mas/configure-app.yml
  vars:
    mas_app_id: manage
    mas_workspace_id: masdev
