---
# Add MSO application to an existing MAS Core installation (see oneclick_core playbook)
- hosts: localhost
  any_errors_fatal: true

  vars:
    mas_workspace_id: masdev
    mas_app_id: mso

  pre_tasks:
    # For the full set of supported environment variables refer to the playbook documentation
    - name: Check for required environment variables
      assert:
        that:
          - lookup('env', 'MAS_INSTANCE_ID') != ""
          - lookup('env', 'MAS_CONFIG_DIR') != ""
        fail_msg: "One or more required environment variables are not defined"

  roles:
    - ibm.mas_devops.suite_app_install
    - ibm.mas_devops.suite_app_config
