---
# Add Monitor 8.7.x application to an existing MAS Core 8.7.x + IoT 8.4.x installation
#
# Dependencies:
# - ansible-playbook ibm.mas_devops.oneclick_core
# - ansible-playbook ibm.mas_devops.oneclick_iot
#
# Monitor will be configured to use the same db2 instance that IoT is using
#
- hosts: localhost
  any_errors_fatal: true

  vars:
    # Application Installation
    mas_app_id: monitor
    mas_app_channel: 8.7.x

    # Application Configuration
    mas_workspace_id: masdev

  pre_tasks:
    # For the full set of supported environment variables refer to the playbook documentation
    - name: Check for required environment variables
      assert:
        that:
          - lookup('env', 'MAS_INSTANCE_ID') != ""
          - lookup('env', 'MAS_ENTITLEMENT_KEY') != ""
        fail_msg: "One or more required environment variables are not defined"

  roles:
    - ibm.mas_devops.suite_app_install
    - ibm.mas_devops.suite_app_config
