---
# Add IoT 8.4.x application to an existing MAS Core 8.7.x installation
#
# Dependencies:
# - ansible-playbook ibm.mas_devops.oneclick_core
#
- hosts: localhost
  any_errors_fatal: true

  vars:
    # Application Dependencies
    db2_instance_name: db2w-shared

    # Application Installation
    mas_app_id: iot
    mas_app_channel: 8.4.x

    # Application Configuration
    mas_workspace_id: masdev

  pre_tasks:
    # For the full set of supported environment variables refer to the playbook documentation
    - name: Check for required environment variables
      assert:
        that:
          - lookup('env', 'MAS_INSTANCE_ID') != ""
          - lookup('env', 'MAS_CONFIG_DIR') != ""
          - lookup('env', 'MAS_ENTITLEMENT_KEY') != ""
        fail_msg: "One or more required environment variables are not defined"

  roles:
    - ibm.mas_devops.db2
    - ibm.mas_devops.kafka
    - ibm.mas_devops.suite_config
    - ibm.mas_devops.suite_app_install
    - ibm.mas_devops.suite_app_config
