---
# MAS 8.7.0 upgrade is more complicated than we would have liked, to this end we
# have provided this playbook to perform a complete upgrade of MAS and all it's
# dependencies to allows customers to more easily move from MAS v8.6 to MAS v8.7.
#
# Dependencies:
# - Certificate Manager .............  1.2 (JetStack) -> 1.5 (IBM)
# - Service Binding Operator ........ 0.8 -> 1.0
# - CloudPak for Data ............... 3.5 -> 4.0
# - OpenShift Container Platform .... 4.6 -> 4.8
#
# MAS:
# - Core ......... 8.6 -> 8.7
# - IoT .......... ?
# - Predict ...... ?
# - Monitor ...... ?
# - Manage ....... ?
# - MSO .......... ?
# - Assist ....... ?
# - MVI .......... ?
# - Others? ...... ?
#
# More Information: <Link to official IBM doc for upgrade>
#
- hosts: localhost
  any_errors_fatal: true
  vars:
    # This flag will instruct 'ibm.mas_devops.suite_dns' to reinstall cis
    # webhook under 'ibm-common-services' ns if 'MAS_CUSTOM_CLUSTER_ISSUER'
    # is set
    is_suite_upgrade: true
  roles:
    # 1. Check that the requirements to upgrade are met
    # -------------------------------------------------------------------------
    - ibm.mas_devops.suite_upgrade_check

    # 2. Migrate from Cert Manager to IBM Cert Manager in the cluster
    # -------------------------------------------------------------------------
    - ibm.mas_devops.cert_manager_upgrade

    # 3. Re-install the Cloud Internet Services webhook for IBM Certificate Manager
    # -------------------------------------------------------------------------
    - ibm.mas_devops.suite_dns

    # 4. Note sure .. ??
    # -------------------------------------------------------------------------
    - ibm.mas_devops.cert_manager_upgrade_check

    # 5. Upgrade from CP4D v3.5 to v4.0
    # -------------------------------------------------------------------------
    - ibm.mas_devops.cp4d_upgrade

    # 6. Upgrade from MAS v8.6 to v8.7
    # -------------------------------------------------------------------------
    - ibm.mas_devops.suite_upgrade

    # 7. Upgrade from OCP v4.6 to v4.8
    # -------------------------------------------------------------------------
    # IIRC this is a ROKS-specific upgrade role, rather than something driven
    # by OCP naturally that would be portable
    - ibm.mas_devops.ocp_upgrade

    # 8. Upgrade from SBO v0.8 to v1.0
    # -------------------------------------------------------------------------
    # Do we even need this, if 0.8 works fine (given we are going to eliminate
    # SBO in v8.8 anyway due to the problems with v1.0)
    - ibm.mas_devops.sbo_upgrade
