---
# tasks file for ocs_power 
- name: "Connect to bastion host"
  shell: | 
   sshpass -p $FYRE_PASSWORD scp -r ../roles/ocs_power/templates root@api.$CLUSTER_NAME.cp.fyre.ibm.com:/root/nfs
   sshpass -p $FYRE_PASSWORD ssh -T root@api.$CLUSTER_NAME.cp.fyre.ibm.com <<'EOL'
   yum install -y -q nfs-utils &&
   wget -q https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_ppc64le &&
   chmod +x yq_linux_ppc64le &&
   mv yq_linux_ppc64le /usr/bin/yq &&
   firewall-cmd --permanent --add-service=nfs &&
   firewall-cmd --permanent --add-service=rpc-bind &&
   firewall-cmd --permanent --add-service=mountd &&
   EXPORTS=/etc/exports &&
   mkdir -p "../nfsshare/nfsshare/cY" &&
   chmod -R 755 "../nfsshare/nfsshare/cY" &&
   exportfs -rav &&
   systemctl restart nfs-server &&
   oc apply -f nfs/namespace.yaml &&
   oc apply -f nfs/nfs-provisioner-rbac.yaml &&
   oc adm policy add-scc-to-user hostmount-anyuid system:serviceaccount:nfs-provisioner:nfs-client-provisioner &&
   oc apply -f nfs/nfs-provisioner-sc.yaml &&
   oc create configmap ip-env --from-literal=ipaddress=$(hostname -i) &&
   oc apply -f nfs/nfs-provisioner-deployment.yaml
   EOL

