---

# cluster_name has no default, it must be passed in
cluster_name: "{{ lookup('env', 'CLUSTER_NAME')}}"

# cluster_type has no default, it must be passed in
cluster_type: "{{ lookup('env', 'CLUSTER_TYPE')}}"

# What cluster types does this role support
supported_cluster_types:
  - roks
  - quickburn

# ROKS defaults
ibmcloud_apikey: "{{ lookup('env', 'IBMCLOUD_APIKEY') }}"

# Quickburn defaults
username: "{{ lookup('env', 'FYRE_USERNAME') }}"
password: "{{ lookup('env', 'FYRE_APIKEY') }}"
