galaxy_info:
  author: Yong Chao LI
  description: Install and Config WDS for IBM MAS Assist
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibm
    - mas
    - devops
    - wds

dependencies: []
