---
# tasks file for ocs_power
- name: "ocs-power : Create Namespace"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/localstorage/namespace.yaml') }}"
  register: namespace

- name: "ocs_power : Apply Role Bindings"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/nfs-provisioner-rbac.yaml') }}"
  register: nfs-rbac

- name: "ocs_power : User policy"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/userpolicy.yaml') }}"

- name: "ocs_power : Apply deployment"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/nfs-provisioner-deployment.yaml') }}"
  register: nfs-deployment

- name: "ocs_power : Apply SC"
  kubernetes.core.k8s:
    apply: yes
    definition: "{{ lookup('template', 'templates/nfs-provisioner-sc.yaml') }}"
  register: nfs-sc


