---
cpd_version: "{{ lookup('env', 'CPD_VERSION') }}"
cpd_storage_class: "{{ lookup('env', 'CPD_STORAGE_CLASS') }}"
cpd_wd_storage_class: "{{ lookup('env', 'CPD_WD_STORAGE_CLASS') }}"
cpd_admin_username: admin

# MAS Configuration
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"
