---
cpd_version: "{{ lookup('env', 'CPD_VERSION') }}"
cpd_storage_class: "{{ lookup('env', 'CPD_STORAGE_CLASS') }}"
cpd_wd_storage_class: "{{ lookup('env', 'CPD_WD_STORAGE_CLASS') }}"
cpd_admin_username: admin

# MAS Configuration
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"

# CPD Watson Studio default properties
cpd_wsl_project_id: "{{ lookup('env', 'CPD_WSL_PROJECT_ID') }}" # if undefined or if the one provided does not exist, one new ws project will be created
cpd_wsl_project_name: "{{ lookup('env', 'CPD_WSL_PROJECT_NAME') | default('ws_default_project', true) }}"
cpd_wsl_project_description: "{{ lookup('env', 'CPD_WSL_PROJECT_DESCRIPTION') | default('Watson Studio project to be used by HP Utilities app in MAS', true) }}"
storage_guid: "{{ 1000 | random | to_uuid | lower }}"
