---
# Default application spec for HPUtilities
mas_app_ws_spec:
  bindings:
    watsonstudio: system
  components: '{{ mas_appws_components | default({}, true) }}'
  settings:
    watsonstudio:
      projectid: "{{ cpd_wsl_project_id }}" # this will be set in mas_devops.cp4d_install_services (either via env var in defaults/main.yml or created via rest api
