---
# Application specific variables for IoT
mas_app_fqn: iots.iot.ibm.com
mas_app_api_version: iot.ibm.com/v1
mas_app_kind: IoT

mas_app_install_timeout: 120  # 2 minutes before we give up and fall back into the retry loop
mas_app_install_retries: 30   # 2 mins each loop * 30 loops =~ 1 hour
