---
# Application specific variables for Maximo Scheduler Optimization (MSO)
mas_app_fqn: msoapps.apps.mas.ibm.com
mas_app_api_version: apps.mas.ibm.com/v1
mas_app_kind: MSOApp

mas_app_install_timeout: 120  # 2 minutes before we give up and fall back into the retry loop
mas_app_install_retries: 10   # 2 mins each loop * 10 loops =~ 20 minutes
