---
iot:
  apiVersion: iot.ibm.com/v1
  crdkind: IoT
  wskind: IoTWorkspace
manage:
  apiVersion: apps.mas.ibm.com/v1
  crdkind: ManageApp
  wskind: ManageWorkspace
monitor:
  apiVersion: apps.mas.ibm.com/v1
  crdkind: MonitorApp
  wskind: MonitorWorkspace
predict:
  apiVersion: apps.mas.ibm.com/v1
  crdkind: PredictApp
  wskind: PredictWorkspace
safety:
  apiVersion: apps.mas.ibm.com/v1
  crdkind: Safety
  wskind: SafetyWorkspace
hputilities:
  apiVersion: apps.mas.ibm.com/v1
  crdkind: HPUtilitiesApp
  wskind: HPUtilitiesWorkspace
assist:
  apiVersion: apps.mas.ibm.com/v1
  crdkind: AssistApp
  wskind: AssistWorkspace
