---
uds_storage_class: "{{ lookup('env', 'UDS_STORAGE_CLASS') }}"
uds_event_scheduler_frequency: "{{ lookup('env', 'UDS_EVENT_SCHEDULER_FREQUENCY') | default('@daily', true) }}"

# bas_username: "{{ lookup('env', 'BAS_USERNAME') | default('basuser', true) }}"
# bas_password: "{{ lookup('env', 'BAS_PASSWORD') }}"

# bas_grafana_username: "{{ lookup('env', 'BAS_GRAFANA_USERNAME') | default('basuser', true) }}"
# bas_grafana_password: "{{ lookup('env', 'BAS_GRAFANA_PASSWORD') }}"

uds_contact:
  email: "{{ lookup('env', 'UDS_CONTACT_EMAIL') }}"
  first_name: "{{ lookup('env', 'UDS_CONTACT_FIRSTNAME') }}"
  last_name: "{{ lookup('env', 'UDS_CONTACT_LASTNAME') }}"

# MAS Configuration
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_config_dir: "{{ lookup('env', 'MAS_CONFIG_DIR') }}"

# Entirely optional, MAS has a built-in segment key, that can be overridden in the BASCfg
mas_segment_key: "{{ lookup('env', 'MAS_SEGMENT_KEY') }}"
