---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mas-devops-cert-manager
spec:
  params:
    - name: junit_suite_name
      type: string
      description: Optional name for the junit suite, used to enable save-junit-to-mongo.py
      default: ""
    - name: mas_channel
      type: string

  stepTemplate:
    env:
      - name: JUNIT_SUITE_NAME
        value: $(params.junit_suite_name)
      - name: MAS_CHANNEL
        value: $(params.mas_channel)

  steps:
    - name: cert-manager
      command:
        - /opt/app-root/src/run-role.sh
        - cert_manager
      image: quay.io/ibmmas/ansible-devops:latest
      imagePullPolicy: Always
      workingDir: /workspace/configs
