---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mas-devops-common-services
spec:
  params:
    - name: junit_suite_name
      type: string
      description: Optional name for the junit suite, used to enable save-junit-to-mongo.py
      default: ""

  stepTemplate:
    env:
      - name: JUNIT_SUITE_NAME
        value: $(params.junit_suite_name)

  steps:
    - name: common-services
      command:
        - /opt/app-root/src/run-role.sh
        - common_services
      image: quay.io/ibmmas/ansible-devops:latest
      imagePullPolicy: Always
      workingDir: /workspace/configs
