---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mas-devops-cos
spec:
  params:
    - name: junit_suite_name
      type: string
      description: Optional name for the junit suite, used to enable save-junit-to-mongo.py
      default: ""
    - name: mas_instance_id
      type: string

  stepTemplate:
    env:
      - name: JUNIT_SUITE_NAME
        value: $(params.junit_suite_name)
      - name: MAS_INSTANCE_ID
        value: $(params.mas_instance_id)

  steps:
    - name: cos
      command:
        - /opt/app-root/src/run-role.sh
        - cos
      image: quay.io/ibmmas/ansible-devops:latest
      imagePullPolicy: Always
      workingDir: /workspace/configs
