---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mas-devops-gencfg-workspace
spec:
  params:
    - name: junit_suite_name
      type: string
      description: Optional name for the junit suite, used to enable save-junit-to-mongo.py
      default: ""
    - name: mas_instance_id
      type: string
      description: Instance ID
    - name: mas_workspace_id
      type: string
      description: Workspace ID
    - name: mas_workspace_name
      type: string
      description: Workspace Name

  stepTemplate:
    env:
      - name: JUNIT_SUITE_NAME
        value: $(params.junit_suite_name)
      - name: MAS_CONFIG_DIR
        value: /workspace/configs
      - name: MAS_INSTANCE_ID
        value: $(params.mas_instance_id)
      - name: MAS_WORKSPACE_ID
        value: $(params.mas_workspace_id)
      - name: MAS_WORKSPACE_NAME
        value: $(params.mas_workspace_name)

  steps:
    - name: gencfg-workspace
      command:
        - /opt/app-root/src/run-role.sh
        - gencfg_workspace
      image: quay.io/ibmmas/ansible-devops:latest
      imagePullPolicy: Always
      workingDir: /workspace/configs

  workspaces:
    - name: configs
