---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mas-devops-ibm-catalogs
spec:
  params:
    - name: junit_suite_name
      type: string
      description: Optional name for the junit suite, used to enable save-junit-to-mongo.py
      default: ""

    - name: artifactory_username
      default: ''
      type: string
      description: Required to install development MAS catalogs
    - name: artifactory_apikey
      default: ''
      type: string
      description: Required to install development MAS catalogs

  stepTemplate:
    env:
      - name: JUNIT_SUITE_NAME
        value: $(params.junit_suite_name)

      - name: ARTIFACTORY_USERNAME
        value: $(params.artifactory_username)
      - name: ARTIFACTORY_APIKEY
        value: $(params.artifactory_apikey)

  steps:
    - name: ibm-catalogs
      command:
        - /opt/app-root/src/run-role.sh
        - ibm_catalogs
      image: quay.io/ibmmas/ansible-devops:latest
      imagePullPolicy: Always
      workingDir: /workspace/configs
