---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mas-devops-kafka
spec:
  params:
    - name: junit_suite_name
      type: string
      description: Optional name for the junit suite, used to enable save-junit-to-mongo.py
      default: ""

    - name: mas_instance_id
      type: string
      description: Instance ID
      default: "" # By default, no config will be generated

    - name: kafka_namespace
      type: string
      default: "amq-streams"
    - name: kafka_cluster_name
      type: string
      default: "maskafka"
    - name: kafka_cluster_size
      type: string
      default: "small"
    - name: kafka_user_name
      type: string
      default: "masuser"

  stepTemplate:
    env:
      - name: JUNIT_SUITE_NAME
        value: $(params.junit_suite_name)

      - name: MAS_CONFIG_DIR
        value: /workspace/configs
      - name: MAS_INSTANCE_ID
        value: $(params.mas_instance_id)

      - name: KAFKA_NAMESPACE
        value: $(params.kafka_namespace)
      - name: KAFKA_CLUSTER_NAME
        value: $(params.kafka_cluster_name)
      - name: KAFKA_CLUSTER_SIZE
        value: $(params.kafka_cluster_size)
      - name: KAFKA_USER_NAME
        value: $(params.kafka_user_name)

  steps:
    - name: kafka
      command:
        - /opt/app-root/src/run-role.sh
        - kafka
      image: quay.io/ibmmas/ansible-devops:latest
      imagePullPolicy: Always
      workingDir: /workspace/configs

  workspaces:
    - name: configs
