---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mas-devops-mongodb
spec:
  params:
    - name: junit_suite_name
      type: string
      description: Optional name for the junit suite, used to enable save-junit-to-mongo.py
      default: ""

    - name: mas_instance_id
      type: string
      description: Instance ID
      default: "" # By default, no config will be generated

  stepTemplate:
    env:
      - name: JUNIT_SUITE_NAME
        value: $(params.junit_suite_name)
      - name: MAS_CONFIG_DIR
        value: /workspace/configs
      - name: MAS_INSTANCE_ID
        value: $(params.mas_instance_id)

  steps:
    - name: mongodb
      command:
        - /opt/app-root/src/run-role.sh
        - mongodb
      image: quay.io/ibmmas/ansible-devops:latest
      imagePullPolicy: Always
      workingDir: /workspace/configs

  workspaces:
    - name: configs
