---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mas-devops-sls
spec:
  params:
    - name: junit_suite_name
      type: string
      description: Optional name for the junit suite, used to enable save-junit-to-mongo.py
      default: ""

    - name: mas_instance_id
      type: string
      description: Instance ID
      default: "" # By default, no config will be generated

    - name: sls_license_id
      type: string
    - name: sls_license_file
      type: string
    - name: sls_mongodb_cfg_file
      type: string
    - name: sls_icr_cp
      type: string
      default: ""
    - name: sls_icr_cpopen
      type: string
      default: ""
    - name: sls_entitlement_username
      type: string
      default: ""
    - name: sls_entitlement_key
      type: string

    - name: artifactory_username
      default: ''
      type: string
      description: Required to use development MAS builds
    - name: artifactory_apikey
      default: ''
      type: string
      description: Required to use development MAS builds

  stepTemplate:
    env:
      - name: JUNIT_SUITE_NAME
        value: $(params.junit_suite_name)

      - name: MAS_CONFIG_DIR
        value: /workspace/configs
      - name: MAS_INSTANCE_ID
        value: $(params.mas_instance_id)

      - name: SLS_MONGODB_CFG_FILE
        value: $(params.sls_mongodb_cfg_file)
      - name: SLS_LICENSE_ID
        value: $(params.sls_license_id)
      - name: SLS_LICENSE_FILE
        value: $(params.sls_license_file)
      - name: SLS_ICR_CP
        value: $(params.sls_icr_cp)
      - name: SLS_ICR_CPOPEN
        value: $(params.sls_icr_cpopen)
      - name: SLS_ENTITLEMENT_USERNAME
        value: $(params.sls_entitlement_username)
      - name: SLS_ENTITLEMENT_KEY
        value: $(params.sls_entitlement_key)

      - name: ARTIFACTORY_USERNAME
        value: $(params.artifactory_username)
      - name: ARTIFACTORY_APIKEY
        value: $(params.artifactory_apikey)

  steps:
    - name: sls
      command:
        - /opt/app-root/src/run-role.sh
        - sls
      image: quay.io/ibmmas/ansible-devops:latest
      imagePullPolicy: Always
      workingDir: /workspace/configs

  workspaces:
    - name: configs
    - name: entitlement
