---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mas-devops-suite-install
spec:
  params:
    - name: junit_suite_name
      type: string
      description: Optional name for the junit suite, used to enable save-junit-to-mongo.py
      default: ""

    - name: mas_instance_id
      type: string
    - name: mas_channel
      type: string
    - name: mas_catalog_source
      type: string
      default: ""

    - name: mas_icr_cp
      type: string
      default: ""
    - name: mas_icr_cpopen
      type: string
      default: ""

    - name: mas_entitlement_username
      type: string
      default: ""
    - name: mas_entitlement_key
      type: string

    - name: artifactory_username
      default: ''
      type: string
      description: Required to install development MAS catalogs
    - name: artifactory_apikey
      default: ''
      type: string
      description: Required to install development MAS catalogs

  stepTemplate:
    env:
      - name: JUNIT_SUITE_NAME
        value: $(params.junit_suite_name)

      - name: MAS_CONFIG_DIR
        value: /workspace/configs
      - name: MAS_INSTANCE_ID
        value: $(params.mas_instance_id)
      - name: MAS_CHANNEL
        value: $(params.mas_channel)
      - name: MAS_CATALOG_SOURCE
        value: $(params.mas_catalog_source)

      - name: ARTIFACTORY_USERNAME
        value: $(params.artifactory_username)
      - name: ARTIFACTORY_APIKEY
        value: $(params.artifactory_apikey)

      - name: MAS_ICR_CP
        value: $(params.mas_icr_cp)
      - name: MAS_ICR_CPOPEN
        value: $(params.mas_icr_cpopen)

      - name: MAS_ENTITLEMENT_USERNAME
        value: $(params.mas_entitlement_username)
      - name: MAS_ENTITLEMENT_KEY
        value: $(params.mas_entitlement_key)

  steps:
    - name: suite-install
      command:
        - /opt/app-root/src/run-role.sh
        - suite_install
      image: quay.io/ibmmas/ansible-devops:latest
      imagePullPolicy: Always
      workingDir: /workspace/configs

  workspaces:
    - name: configs
    - name: additional-configs
