---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mas-devops-suite-app-config
spec:
  params:
    - name: junit_suite_name
      type: string
      description: Optional name for the junit suite, used to enable save-junit-to-mongo.py
      default: ""
    - name: mas_app_id
      type: string
      description: Maximo Application Suite Application ID
    - name: mas_appws_components
      type: string
      description: Components to configure in the workspace
      default: ""
    - name: mas_instance_id
      type: string
      description: Instance ID
    - name: mas_workspace_id
      type: string
      description: Maximo Application Suite Workspace ID
  stepTemplate:
    env:
      - name: JUNIT_SUITE_NAME
        value: $(params.junit_suite_name)
      - name: MAS_INSTANCE_ID
        value: $(params.mas_instance_id)
      - name: MAS_WORKSPACE_ID
        value: $(params.mas_workspace_id)
      - name: MAS_APP_ID
        value: $(params.mas_app_id)
      - name: MAS_APPWS_COMPONENTS
        value: $(params.mas_appws_components)
  steps:
    - name: suite-app-config
      command:
        - /opt/app-root/src/run-role.sh
        - suite_app_config
      image: quay.io/ibmmas/ansible-devops:latest
      imagePullPolicy: Always
