---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mas-devops-uds
spec:
  params:
    - name: junit_suite_name
      type: string
      description: Optional name for the junit suite, used to enable save-junit-to-mongo.py
      default: ""
    - name: mas_instance_id
      type: string
      default: ""
    - name: uds_contact_email
      type: string
      default: ""
    - name: uds_contact_firstname
      type: string
      default: ""
    - name: uds_contact_lastname
      type: string
      default: ""

  stepTemplate:
    env:
      - name: JUNIT_SUITE_NAME
        value: $(params.junit_suite_name)
      - name: MAS_CONFIG_DIR
        value: /workspace/configs
      - name: MAS_INSTANCE_ID
        value: $(params.mas_instance_id)
      - name: UDS_CONTACT_EMAIL
        value: $(params.uds_contact_email)
      - name: UDS_CONTACT_FIRSTNAME
        value: $(params.uds_contact_firstname)
      - name: UDS_CONTACT_LASTNAME
        value: $(params.uds_contact_lastname)

  steps:
    - name: uds
      command:
        - /opt/app-root/src/run-role.sh
        - uds
      image: quay.io/ibmmas/ansible-devops:latest
      imagePullPolicy: Always
      workingDir: /workspace/configs

  workspaces:
    - name: configs
