# db2 restore default vars
db2wh_backup_dir: "{{ lookup('env', 'DB2WH_BACKUP_DIR') }}"
db2wh_instance_name: "{{ lookup('env', 'DB2WH_INSTANCE_NAME_TARGET') }}"
# temporary vars to be used during restore process in db2wh pod
db2wh_temp_backup_dir: /tmp/db_backup
db2wh_db2inst1_backup_dir: /mnt/blumeta0/home/db2inst1/db_backup
db2wh_temp_backup_logs_dir: /tmp/db_backup_logs
# Default name for ConfigMap created by this automation role inside CP4D namespace
# Make sure it matches the value used in cp4d_db2wh_api role
cp4d_db_config_configmap_name: mas-automation-config
