---

# 1. Failure conditions
# -----------------------------------------------------------------------------
- name: "quickburn : Fail if required properties are not provided"
  assert:
    that:
      - fyre_cluster_size is defined and fyre_cluster_size != ""
      - fyre_product_id is defined and fyre_product_id != ""
      - fyre_username is defined and fyre_username != ""
      - fyre_password is defined and fyre_password != ""
    fail_msg: "One or more required properties are missing"


# 2. Debug Info
# -----------------------------------------------------------------------------
- name: "quickburn : Debug information"
  debug:
    msg:
      - "Cluster name ................. {{ cluster_name }}"
      - "OCP version .................. {{ ocp_version }}"
      - "Username ..................... {{ fyre_username }}"
      - "Password ..................... *********************"
      # Quickburn specific
      - "Fyre product ID .............. {{ fyre_product_id }}"
      - "Fyre cluster size ............ {{ fyre_cluster_size }}"


# 3. Determine whether there is already a quickburn environment running
# -----------------------------------------------------------------------------
- name: "quickburn : Check if cluster already exists"
  uri:
    url: "https://ocpapi.svl.ibm.com/v1/ocp/{{cluster_name}}"
    user: "{{fyre_username}}"
    password: "{{fyre_password}}"
    method: GET
    force_basic_auth: yes
    validate_certs: false
  register: _cluster_exist
  failed_when: _cluster_exist.status == 403


# 4. Deploy the quick burn cluster
# -----------------------------------------------------------------------------
- name: "quickburn : Create new quick burn cluster"
  when:
    - _cluster_exist.json.cluster_count is not defined
  uri:
    url: https://ocpapi.svl.ibm.com/v1/ocp/
    user: "{{fyre_username}}"
    password: "{{fyre_password}}"
    method: POST
    body: "{{ lookup('template','templates/quickburn.json') }}"
    force_basic_auth: yes
    body_format: json
    validate_certs: false


# 5. Track the progress of the deployment
# -----------------------------------------------------------------------------
- name: "quickburn : Follow deployment status (~20-30 mins)"
  uri:
    url: "https://ocpapi.svl.ibm.com/v1/ocp/{{cluster_name}}/status"
    user: "{{fyre_username}}"
    password: "{{fyre_password}}"
    method: GET
    force_basic_auth: yes
    validate_certs: false
  register: _result
  until:
    - _result.json is defined
    - _result.json.deployed_status == 'deployed'
  retries: 80 # 80 * 30 seconds = 40 minutes
  delay: 30 # Every 30 seconds
