---
apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: mas-devops-configure-app
spec:
  params:
    - name: junit_suite_name
      type: string
      description: Optional name for the junit suite, used to enable save-junit-to-mongo.py
      default: ""
    - name: mas_app_id
      type: string
      description: Maximo Application Suite Application ID
    - name: mas_appws_components
      type: string
      description: Components to configure in the workspace
      default: ""
    - name: mas_workspace_id
      type: string
      description: Maximo Application Suite Workspace ID
  stepTemplate:
    env:
      - name: MAS_CONFIG_DIR
        value: /workspace/configs
      - name: JUNIT_SUITE_NAME
        value: $(params.junit_suite_name)
      - name: MAS_WORKSPACE_ID
        value: $(params.mas_workspace_id)
      - name: MAS_APP_ID
        value: $(params.mas_app_id)
      - name: MAS_APPWS_COMPONENTS
        value: $(params.mas_appws_components)

  steps:
    - name: configure-app
      command:
        - /opt/app-root/src/run-playbook.sh
        - /opt/app-root/playbooks/mas/configure-app.yml
      image: quay.io/ibmmas/ansible-devops:latest
      imagePullPolicy: Always
      workingDir: /workspace/configs

  workspaces:
    - name: settings
