apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  # replace with namespace where provisioner is deployed
  namespace: nfs-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          # nfs client provisioner image specific to the architecture
          image: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: nfs-storage-provisioner
              # must match provisioner name in storage class
              value: nfs-storage
            - name: NFS_SERVER 
              # ip address of nfs server
              valueFrom:
                configMapKeyRef:
                  name: ip-env
                  key: ipaddress
            - name: NFS_PATH 
              # shared folder on nfs server
              value: "/nfsshare/nfsshare/cY"
      volumes:
        - name: nfs-client-root
          valueFrom:
            configMapKeyRef:
              name: ip-env
              key: ipaddress
          path: "/nfsshare/nfsshare/cY"
