---
#oc adm policy add-scc-to-user hostmount-anyuid system:serviceaccount:${nfsnamespace}:nfs-client-provisioner

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nfs_client_anyuid
  namespace: nfs-provisioner
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - hostmount-anyuid
