# Usage: oc apply -f fvt-pipelinesettings-roks.yaml -n <mynamespace>
# Tip: use yj command line tool to modify this in automation
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pipeline-settings
  namespace: mas-sample-pipelines
stringData:
  # ---------------------------------------------------------------------------
  # These are all global settings that will apply to every stage
  # Additional task-scoped settings can be provided via parameters in the Tasks
  #
  # Additional variables are supported, this is a minimum required set
  # ---------------------------------------------------------------------------

  # -------------------------
  # ocp/configure-ocp.yml
  # -------------------------
  W3_USERNAME: "$W3_USERNAME"
  ARTIFACTORY_APIKEY: "$ARTIFACTORY_APIKEY"

  IBMCLOUD_APIKEY: "$IBMCLOUD_APIKEY"

  PROMETHEUS_STORAGE_CLASS: "ibmc-block-gold"
  PROMETHEUS_ALERTMGR_STORAGE_CLASS: "ibmc-file-gold-gid"

  # -------------------------
  # dependencies/install-mongodb-ce.yml
  # -------------------------
  MAS_INSTANCE_ID: "$MAS_INSTANCE_ID"
  MONGODB_STORAGE_CLASS: "ibmc-block-gold"

  # -------------------------
  # cp4d/install-cp4d.yml
  # -------------------------
  CPD_ENTITLEMENT_KEY: "$CPD_ENTITLEMENT_KEY"
  CPD_STORAGE_CLASS: "ibmc-file-gold-gid"
  CPD_BLOCK_STORAGE_CLASS: "ibmc-block-gold"

  # -------------------------
  # cp4d/create-db2-instance.yml
  # -------------------------
  DB2WH_META_STORAGE_CLASS: "ibmc-file-silver-gid"
  DB2WH_USER_STORAGE_CLASS: "ibmc-file-gold-gid"
  DB2WH_BACKUP_STORAGE_CLASS: "ibmc-file-gold-gid"
  DB2WH_LOGS_STORAGE_CLASS: "ibmc-file-silver-gid"
  DB2WH_TEMP_STORAGE_CLASS: "ibmc-file-silver-gid"

  # -------------------------
  # dependencies/install-amqstreams.yml
  # -------------------------
  KAFKA_STORAGE_CLASS: "ibmc-block-gold"
  KAFKA_NAMESPACE: "amq-streams"
  KAFKA_CLUSTER_NAME: "maskafka"
  KAFKA_CLUSTER_SIZE: "small"
  KAFKA_USER_NAME: "masuser"

  # -------------------------
  # dependencies/install-sls.yml
  # -------------------------
  SLS_MONGODB_CFG_FILE: "/workspace/configs/mongo-mongoce.yml"
  SLS_LICENSE_ID: "$SLS_LICENSE_ID"
  SLS_STORAGE_CLASS: "ibmc-file-gold-gid"
  SLS_ICR_CP: "$SLS_ICR_CP"
  SLS_ICR_CPOPEN: "$SLS_ICR_CPOPEN"
  SLS_ENTITLEMENT_USERNAME: "$SLS_ENTITLEMENT_USERNAME"
  SLS_ENTITLEMENT_KEY: "$SLS_ENTITLEMENT_KEY"
  SLS_LICENSE_FILE: "/workspace/entitlement/entitlement.lic"

  # -------------------------
  # dependencies/install-uds.yml
  # -------------------------
  UDS_STORAGE_CLASS: "ibmc-block-bronze"
  UDS_CONTACT_EMAIL: "$UDS_CONTACT_EMAIL"
  UDS_CONTACT_FIRSTNAME: "$UDS_CONTACT_FIRSTNAME"
  UDS_CONTACT_LASTNAME: "$UDS_CONTACT_LASTNAME"

  # -------------------------
  # mas/install-suite.yml
  # -------------------------
  MAS_CATALOG_SOURCE: "$MAS_CATALOG_SOURCE"
  MAS_CHANNEL: "$MAS_CHANNEL"
  MAS_ICR_CP: "$MAS_ICR_CP"
  MAS_ICR_CPOPEN: "$MAS_ICR_CPOPEN"
  MAS_ENTITLEMENT_USERNAME: "$MAS_ENTITLEMENT_USERNAME"
  MAS_ENTITLEMENT_KEY: "$MAS_ENTITLEMENT_KEY"

  # -------------------------
  # mas/configure-app.yml
  # -------------------------
  MAS_WORKSPACE_ID: "masdev"
