# Usage: oc apply -f fvt-pipelinesettings-roks.yaml -n <mynamespace>
# Tip: use yj command line tool to modify this in automation
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pipeline-settings
  namespace: mas-sample-pipelines
stringData:
  # ---------------------------------------------------------------------------
  # These are all global settings that will apply to every stage
  # Additional task-scoped settings can be provided via parameters in the Tasks
  #
  # Many values can be left set to "" to inherit a default, refer to
  # the Ansible playbook documentation for more details
  # ---------------------------------------------------------------------------

  # -------------------------
  # ocp/configure-ocp.yml
  # -------------------------
  # W3_USERNAME and ARTIFACTORY_APIKEY are used to install the pre-release
  # development catalogs, they are not required
  W3_USERNAME: ""
  ARTIFACTORY_APIKEY: ""

  CIS_APIKEY: "<REQUIRED: enter the IBM Cloud Service ID api key here>"
  
  PROMETHEUS_RETENTION_PERIOD: ""
  PROMETHEUS_STORAGE_CLASS: "<REQUIRED: enter a storage class>"
  PROMETHEUS_STORAGE_SIZE: ""
  PROMETHEUS_ALERTMGR_STORAGE_CLASS: "<REQUIRED: enter a storage class>"
  PROMETHEUS_ALERTMGR_STORAGE_SIZE: ""

  # -------------------------
  # dependencies/install-mongodb-ce.yml
  # -------------------------
  MAS_INSTANCE_ID: "<REQUIRED: enter your MAS instance ID here>"
  MAS_CONFIG_DIR: ""
  MONGODB_STORAGE_CLASS: "<REQUIRED: enter a storage class>"
  MONGODB_NAMESPACE: ""
  MONGODB_STORAGE_CAPACITY_DATA: ""
  MONGODB_STORAGE_CAPACITY_LOGS: ""

  # -------------------------
  # cp4d/install-cp4d.yml
  # -------------------------
  CPD_ENTITLEMENT_KEY: "<REQUIRED: enter your IBM entitlement key here>"
  CPD_STORAGE_CLASS: "<REQUIRED: enter a storage class>"
  CPD_BLOCK_STORAGE_CLASS: "<REQUIRED: enter a storage class>"
  CPD_NAMESPACE: ""

  # -------------------------
  # cp4d/create-db2-instance.yml
  # -------------------------
  CPD_API_USER: ""
  CPD_API_PASSWORD: ""

  DB2WH_META_STORAGE_CLASS: "<REQUIRED: enter a storage class>"
  DB2WH_USER_STORAGE_CLASS: "<REQUIRED: enter a storage class>"
  DB2WH_BACKUP_STORAGE_CLASS: "<REQUIRED: enter a storage class>"
  DB2WH_LOGS_STORAGE_CLASS: "<REQUIRED: enter a storage class>"
  DB2WH_TEMP_STORAGE_CLASS: "<REQUIRED: enter a storage class>"

  # The following settings are provided as env vars per-task because they may
  # vary for different tasks in the same pipeline
  # -----------------------------------------------------------------------------
  # - DB2WH_INSTANCE_NAME
  # - DB2WH_VERSION
  # - DB2WH_TABLE_ORG

  # -------------------------
  # dependencies/install-amqstreams.yml
  # -------------------------
  KAFKA_STORAGE_CLASS: "<REQUIRED: enter a storage class>"
  KAFKA_NAMESPACE: "amq-streams"
  KAFKA_CLUSTER_NAME: "maskafka"
  KAFKA_CLUSTER_SIZE: "small"
  KAFKA_USER_NAME: "masuser"

  # -------------------------
  # dependencies/install-sls.yml
  # -------------------------
  SLS_COMPLIANCE_ENFORCE: ""
  SLS_LICENSE_ID: ""
  SLS_STORAGE_CLASS: "<REQUIRED: enter a storage class>"
  SLS_CATALOG_SOURCE: ""
  SLS_CHANNEL: ""
  SLS_NAMESPACE: ""
  SLS_ICR_CP: ""
  SLS_ICR_CPOPEN: ""
  SLS_INSTANCE_NAME: ""
  SLS_ENTITLEMENT_USERNAME: "cp"
  SLS_ENTITLEMENT_KEY: "<REQUIRED: enter your IBM entitlement key here>"
  SLS_DOMAIN: ""
  SLS_AUTH_ENFORCE: ""
  SLS_REGISTRATION_OPEN: ""

  # -------------------------
  # dependencies/install-bas.yml
  # -------------------------
  BAS_NAMESPACE: ""
  BAS_PERSISTENT_STORAGE_CLASS: "<REQUIRED: enter a storage class>"
  BAS_META_STORAGE_CLASS: "<REQUIRED: enter a storage class>"
  BAS_USERNAME: ""
  BAS_PASSWORD: ""
  BAS_GRAFANA_USERNAME: ""
  BAS_GRAFANA_PASSWORD: ""
  BAS_CONTACT_MAIL: "<REQUIRED: enter your email here>"
  BAS_CONTACT_FIRSTNAME: "<REQUIRED: enter your first name here>"
  BAS_CONTACT_LASTNAME: "<REQUIRED: enter your last name here>"
  BAS_EVENT_SCHEDULER_FREQUENCY: ""

  # -------------------------
  # mas/install-suite.yml
  # -------------------------
  CIS_CRN: ""
  CIS_SUBDOMAIN: ""
  MAS_DOMAIN: ""
  MAS_CATALOG_SOURCE: ""
  MAS_CHANNEL: "8.x"
  MAS_ICR_CP: ""
  MAS_ICR_CPOPEN: ""
  MAS_ENTITLEMENT_USERNAME: ""
  MAS_ENTITLEMENT_KEY: "<REQUIRED: enter your IBM entitlement key here>"
  CIS_EMAIL: ""
  CIS_SKIP_DNS_ENTRIES: ""
  CIS_SKIP_CLUSTER_ISSUER: ""
  UPDATE_DNS_ENTRIES: ""
  OCP_INGRESS: ""
  MAS_CUSTOM_CLUSTER_ISSUER: ""
  CERTIFICATE_DURATION: ""
  CERTIFICATE_RENEW_BEFORE: ""
  MAS_CATALOG_IMG: ""
  TM_CATALOG_IMG: ""

  # -------------------------
  # mas/configure-app.yml
  # -------------------------
  MAS_WORKSPACE_ID: ""
