---
- hosts: localhost
  any_errors_fatal: true
  vars:
    # MAS configuration
    mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"

    # MAS workspace configuration
    mas_workspace_id: "{{ lookup('env', 'MAS_WORKSPACE_ID') }}"
    manage_demo_data: "{{ lookup('env', 'MAS_DB_IMPORT_DEMO_DATA') | default( 'false' , true) }}"
    # MAS application configuration
    mas_app_id: "{{ lookup('env', 'MAS_APP_ID') }}"
    mas_appws_jdbc_binding: "{{ lookup('env', 'MAS_APPWS_JDBC_BINDING') }}"

  roles:
    - ibm.mas_devops.suite_app_configure
