---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-namespace-scope-operator
  namespace: "{{ cpd_meta_namespace }}"
spec:
  channel: v3
  installPlanApproval: Automatic
  name: ibm-namespace-scope-operator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
  csvInjector:
    enable: true
  namespaceMembers:
    - "{{ cpd_meta_namespace }}"
 ---
apiVersion: operator.ibm.com/v1alpha1
kind: OperandRequest
metadata:
  name: ibm-db2u-operator
  namespace:"{{ cpd_meta_namespace }}"
  labels:
    app.kubernetes.io/instance: operand-deployment-lifecycle-manager
    app.kubernetes.io/managed-by: operand-deployment-lifecycle-manager
    app.kubernetes.io/name: operand-deployment-lifecycle-manager
  namespace: ibm-common-services
spec:
  requests:
    - operands:
        - name: ibm-db2u-operator
      registry: common-service

