---
apiVersion: wos.cpd.ibm.com/v1
kind: WOService
metadata:
  name: aiopenscale
  namespace: "{{ cpd_services_namespace }}"
spec:
  scaleConfig: small
  license:
    accept: true
    license: Standard    # Specify the license you purchased
  type: service
  storageClass: "{{ cpd_storage_class }}"
  version: 4.0.8 # openscale does not support 'version':'latest' and if we remove 'version', their operator will consider it 'latest', looks like a bug in openscale
