---
# --- MAS channel control ---------------------------------------------------------------------------------------------
# Temporary solution: this will be used to determine whether to install SBO stable channel and the IBM badged cert-manager
# all other channels will install SBO from the stable channel and the IBM Cert Manager (foundation services)
mas_channel: "{{ lookup('env', 'MAS_CHANNEL') }}"
mas_channels_old_releases: ['8.6.x', '8.5.x']
