---
airgap_install: false

# --- Dev catalog settings --------------------------------------------------------------------------------------------
# Only required when using the development catalog sources for pre-release installation
# These are used to set up image pull secret in the openshift-marketplace namespace
artifactory_username: "{{ lookup('env', 'ARTIFACTORY_USERNAME') | lower }}"
artifactory_apikey: "{{ lookup('env', 'ARTIFACTORY_APIKEY') }}"
