apiVersion: cpd.ibm.com/v1
kind: Ibmcpd
metadata:
  name: ibmcpd-cr
  namespace: "{{ cpd_services_namespace }}"
spec:
  license:
    accept: true
    license: Standard
  # https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=requirements-storage
  storageClass: "{{ cpd_storage_class }}"
  zenCoreMetadbStorageClass: "{{ cpd_metadb_block_storage_class }}"
