namespace: ibm
name: mas_devops
version: 9.0.0
readme: README.md
authors:
  - David Parker <parkerda@uk.ibm.com>
  - Paul Stone
  - Tom Klapiscak
  - Caio Pereira <caiofcp@br.ibm.com>
  - Joao Paulo Karol Nunes
  - Alexandre Fernandes Quinteiro <alexandre.quinteiro@br.ibm.com>
description: MAS DevOps Ansible Collection
license:
  - EPL-2.0
tags:
  - ibm
  - mas
  - rhocp
dependencies:
  "kubernetes.core": ">=2.2.0,<3.0.0"
  "ibm.cloudcollection": ">=1.37.1,<2.0.0"
repository: https://github.com/ibm-mas/ansible-devops
documentation: https://ibm-mas.github.io/ansible-devops/
homepage: https://ibm-mas.github.io/ansible-devops/
issues: https://github.com/ibm-mas/ansible-devops/issues
build_ignore: []
