---

# Provide intelligent storage class selection to minimize required user knowledge

# 1. Lookup storage class availabiity
# -----------------------------------------------------------------------------
- name: Lookup storage classes
  kubernetes.core.k8s_info:
    api_version: storage.k8s.io/v1
    kind: StorageClass
  register: lookup_storageclasses

- name: "Debug available storage classes"
  debug:
    msg: "{{ lookup_storageclasses | ibm.mas_devops.getResourceNames }}"


# 2. Set Primary Storage (Required)
# -----------------------------------------------------------------------------
- name: Default Primary Storage if not set by user
  when: cpd_primary_storage_class is not defined or cpd_primary_storage_class == ""
  vars:
    # ROKS, OCS, Azure
    supported_storage_classes: [ibmc-file-gold-gid, ocs-storagecluster-cephfs, azurefiles-premium]
  set_fact:
    cpd_primary_storage_class: "{{ lookup_storageclasses | ibm.mas_devops.defaultStorageClass(supported_storage_classes) }}"

- name: Assert that primary storage class has been defined
  assert:
    that: cpd_primary_storage_class is defined and cpd_primary_storage_class != ""
    fail_msg: "cpd_primary_storage_class must be defined"


# 2. Set Metadata Storage (Required)
# -----------------------------------------------------------------------------
- name: Default Metadata Storage if not set by user
  when: cpd_metadata_storage_class is not defined or cpd_metadata_storage_class == ""
  vars:
    # ROKS, OCS, Azure
    supported_storage_classes: [ibmc-block-gold, ocs-storagecluster-ceph-rbd, managed-premium]
  set_fact:
    cpd_metadata_storage_class: "{{ lookup_storageclasses | ibm.mas_devops.defaultStorageClass(supported_storage_classes) }}"

- name: Assert that metadata storage class has been defined
  assert:
    that: cpd_metadata_storage_class is defined and cpd_metadata_storage_class != ""
    fail_msg: "cpd_metadata_storage_class must be defined"


# 3. Debug storage class configuration
# -----------------------------------------------------------------------------
- name: "Debug CP4D storage class configuration"
  debug:
    msg:
      - "Storage class (primary) .......... {{ cpd_primary_storage_class }}"
      - "Storage class (metadata) ......... {{ cpd_metadata_storage_class }}"
