---
# The following playbook is an attempt to automate the CP4D 4.0 steps documented here:
# https://www.ibm.com/support/producthub/icpdata/docs/content/SSQNUZ_latest/cpd/install/preinstall-overview.html


- name: "Run pre-req check"
  include_tasks: "tasks/prereq-check.yml"

- name: "Determine storage classes"
  include_tasks: "tasks/determine-storage-classes.yml"

- name: "Create CP4D Operator Subscriptions"
  include_tasks: "tasks/create-subscriptions.yml"

# At this stage:
# - The two namespaces (ibm-cpd and ibm-cpd-operators) will be created
# - OperatorGroup will have been created in the ibm-cpd-operators namespace
# - Cloud Pak for Data Platform Operator (cpd-platform-operator-manager) v2.0 will be installed in ibm-cpd-operators namespace
# - IBM Cloud Pak Foundational Services (ibm-common-service-operator) v3 will be installed in ibm-cpd-operators namespace
# - IBM NamespaceScope Operator (ibm-namespace-scope-operator) v3 will be installed in ibm-cpd-operators namespace
# - A NamespaceScope will have been created in the ibm-cpd-operators namespace
# - Nothing will exist in the ibm-cpd namespace yet

- name: "Install CP4D"
  include_tasks: "tasks/install-cp4d.yml"

# At this stage:
# - IBM Zen Operator will be installed into the ibm-common-services namespace
# - IBM Cert Manager Operator will be installed into the ibm-common-services namespace
# - Multiple deployments will be put into the ibm-cp4d namespace:
#     - ibm-nginx
#     - usermgmt
#     - zen-audit
#     - zen-core
#     - zen-core-api
#     - zen-data-sorcerer
#     - zen-watchdog
#     - zen-watcher
