---

# Check for required facts
# -----------------------------------------------------------------------------
- name: "Fail if BAS persistent storage class has not been provided"
  when: bas_persistent_storage_class is not defined or bas_persistent_storage_class == ""
  fail:
    msg: "bas_persistent_storage_class property has not been set"

- name: "Fail if BAS block storage class has not been provided"
  when: bas_meta_storage_class is not defined or bas_meta_storage_class == ""
  fail:
    msg: "bas_meta_storage_class property has not been set"

- name: "Fail if BAS email has not been provided"
  when: bas_contact.email is not defined or bas_contact.email == ""
  fail:
    msg: "bas_contact.email property has not been set"

- name: "Fail if BAS first name has not been provided"
  when: bas_contact.firstName is not defined or bas_contact.firstName == ""
  fail:
    msg: "bas_contact.firstName property has not been set"

- name: "Fail if BAS email has not been provided"
  when: bas_contact.lastName is not defined or bas_contact.lastName == ""
  fail:
    msg: "bas_contact.lastName property has not been set"

# 1. Generate BAS related passwords if none provided
# -----------------------------------------------------------------------------
- name: "Generate bas_password if none has been provided"
  when: bas_password is not defined or bas_password == ""
  set_fact:
    bas_password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
  no_log: "{{ bas_password is defined }}"

- name: "Generate bas_grafana_password if none has been provided"
  when: bas_grafana_password is not defined or bas_grafana_password == ""
  set_fact:
    bas_grafana_password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
  no_log: "{{ bas_grafana_password is defined }}"

# 2. Provide Debug information
# -----------------------------------------------------------------------------
- name: "Debug information"
  debug:
    msg:
      - "BAS Namespace ...................... {{ bas_namespace }}"
      - "BAS Persistent Storage Class........ {{ bas_persistent_storage_class }}"
      - "BAS Metadata Storage Class ......... {{ bas_meta_storage_class }}"


# 3. Create BAS project
# -----------------------------------------------------------------------------
- name: "Create namespace"
  community.kubernetes.k8s:
    api_version: v1
    kind: Namespace
    name: '{{ bas_namespace }}'


# 4. Deploy BAS subscription and Operator Group
# -----------------------------------------------------------------------------
- name: "Create operator group"
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'templates/operator-group.yaml') }}"
    wait: yes
    wait_timeout: 60 #subsequent tasks will fail if the CRD isn't fully created

- name: "Create subscription"
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'templates/subscription.yaml') }}"
    wait: yes
    wait_timeout: 300
    wait_condition:
      type: 'CatalogSourcesUnhealthy'
      status: "False"

- name: "Wait until the FullDeployment CRD is available"
  community.kubernetes.k8s_info:
    api_version: apiextensions.k8s.io/v1
    name: "fulldeployments.bas.ibm.com"
    kind: CustomResourceDefinition
    wait: yes
    wait_sleep: 10
    wait_timeout: 300 # 5 mins until we give up waiting for the CRD to get into the expected state
    wait_condition:
      type: NamesAccepted
      status: "True"
  register: bas_crd_info
  retries: 120 # ~approx 10 minutes before we give up waiting for the CRD to be created
  delay: 5 # seconds
  until:
    - bas_crd_info.resources is defined
    - bas_crd_info.resources | length > 0


# 5. Create BAS User Secret
# -----------------------------------------------------------------------------
- name: Create BAS User Secret
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: database-credentials
        namespace: "{{ bas_namespace}}"
      stringData:
        db_username: "{{ bas_username }}"
        db_password: "{{ bas_password }}"
  no_log: "{{ bas_password is defined }}"

# 6. Create Graphana User Secret
# -----------------------------------------------------------------------------
- name: Create Grafana User Secret
  community.kubernetes.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: grafana-credentials
        namespace: "{{ bas_namespace}}"
      stringData:
        bas_grafana_username: "{{ bas_grafana_username }}"
        bas_grafana_password: "{{ bas_grafana_password }}"
  no_log: "{{ bas_grafana_password is defined }}"


# 7. Create BAS Full Deployment
# -----------------------------------------------------------------------------
- name: "Create BAS FullDeployment"
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'templates/fulldeployment.yaml') }}"


# 8. Wait Full Deployment to be complete
# -----------------------------------------------------------------------------
- name: "Wait for FullDeployment to be ready (60s delay)"
  community.kubernetes.k8s_info:
    api_version: bas.ibm.com/v1
    name: fulldeployment
    namespace: "{{bas_namespace}}"
    kind: FullDeployment
  register: bas_cr_result
  until:
    - bas_cr_result.resources is defined and bas_cr_result.resources | length == 1
    - bas_cr_result.resources[0].status is defined
    - bas_cr_result.resources[0].status.phase is defined
    - bas_cr_result.resources[0].status.phase == 'Ready'
  retries: 45 # approx 45 minutes before we give up
  delay: 60 # 1 minute

- name: "Create BAS Generate Key"
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'templates/generateKey.yaml') }}"


# 9. Wait Full Deployment to be complete
# -----------------------------------------------------------------------------
- name: "Wait for GenerateKey to be ready (60s delay)"
  community.kubernetes.k8s_info:
    api_version: bas.ibm.com/v1
    name: bas-api-key
    namespace: "{{bas_namespace}}"
    kind: GenerateKey
  register: bas_gk_result
  until:
    - bas_gk_result.resources is defined and bas_gk_result.resources | length == 1
    - bas_gk_result.resources[0].status is defined
    - bas_gk_result.resources[0].status.phase is defined
    - bas_gk_result.resources[0].status.phase == 'Ready'
  retries: 30 # approx 30 minutes before we give up
  delay: 60 # 1 minute


# 10. MAS Config
# -----------------------------------------------------------------------------
- include_tasks: tasks/bascfg.yml
  when:
    - mas_instance_id is defined
    - mas_instance_id != ""
    - mas_config_dir is defined
    - mas_config_dir != ""

# 11. BAS deployment details
# -----------------------------------------------------------------------------
- name: "BAS Deployment details"
  debug:
    msg:
      - "BAS Namespace ...................... {{ bas_namespace }}"
      - "BAS Endpoint Url ................... {{ bas_endpoint_url}}"
      - "BAS API Key ........................ Found in 'bas_api_key' secret under '{{ bas_namespace }}' namespace"
      - "BAS Username/Password .............. Found in 'database-credentials' secret under '{{ bas_namespace }}' namespace"
      - "BAS Grafana Username/Password ...... Found in 'grafana-credentials' secret under '{{ bas_namespace }}' namespace"
      - "BAS E-mail ......................... {{ bas_contact.email }}"
      - "BAS First Name ..................... {{ bas_contact.firstName }}"
      - "BAS Last Name ...................... {{ bas_contact.lastName }}"
