---
mas_app_ws_fqn: iotworkspaces.iot.ibm.com
mas_app_ws_apiversion: iot.ibm.com/v1
mas_app_ws_kind: IoTWorkspace

mas_app_cfg_timeout: 60  # 1 minute before we give up and fall back into the retry loop
mas_app_cfg_retries: 10  # 1 mins each loop * 10 loops =~ 10 minutes
