---
mas_app_ws_fqn: manageworkspaces.apps.mas.ibm.com
mas_app_ws_apiversion: apps.mas.ibm.com/v1
mas_app_ws_kind: ManageWorkspace

mas_app_cfg_timeout: 480  # 8 minutes before we give up and fall back into the retry loop
mas_app_cfg_retries: 50   # 8 mins each loop * 50 loops =~ 400 minutes / 6 2/3 hours (Manage is really slow to set up)
