---
mas_app_ws_fqn: predictworkspaces.apps.mas.ibm.com
mas_app_ws_apiversion: apps.mas.ibm.com/v1
mas_app_ws_kind: PredictWorkspace

mas_app_cfg_timeout: 120  # 2 minutes before we give up and fall back into the retry loop
mas_app_cfg_retries: 30   # 2 mins each loop * 10 loops =~ 20 minutes
