---
# 1. Lookup the application CR
# --------------------------------------------------------------------------------
- name: "Get installed version of {{ app_upgrade_id }}"
  kubernetes.core.k8s_info:
    api_version: "{{ app_upgrade_version }}"
    name: "{{ mas_instance_id }}"
    namespace: "mas-{{ mas_instance_id }}-{{ app_upgrade_id }}"
    kind: "{{ app_upgrade_kind }}"
  register: app_info

- debug:
    msg: "{{ app_info.msg }}"
  when: app_info.msg is defined

# 2. Change subscription channel
# --------------------------------------------------------------------------------
- name: "Update subscription channel"
  when:
    - app_info.resources is defined
    - app_info.resources | length == 1
  kubernetes.core.k8s:
    api_version: operators.coreos.com/v1alpha1
    name: "ibm-mas-{{ app_upgrade_id }}"
    namespace: "mas-{{ mas_instance_id }}-{{ app_upgrade_id }}"
    kind: Subscription
    definition:
      spec:
        channel: "{{ mas_app_upgrade_target_channels[app_upgrade_id] }}"
    apply: true
  register: app_sub_update

# 3. Generate a list of apps that are being upgraded so we can watch its progress
# --------------------------------------------------------------------------------
- set_fact:
    mas_apps: "{{ mas_apps|default([]) + [app_upgrade_id] }}"
  when:
    - app_info.resources is defined
    - app_info.resources | length == 1
