---
# 1. Upgrade the Subscription for ibm-mas to 8.7.x channel
# -----------------------------------------------------------------------------
# 1.1 Change subscription channel
- name: "Update MAS 8.6 subscription to 8.7.x channel"
  kubernetes.core.k8s:
    api_version: operators.coreos.com/v1alpha1
    name: "ibm-mas-operator"
    namespace: "{{ mas_namespace }}"
    kind: Subscription
    definition:
      spec:
        channel: "{{ mas_upgrade_target_channel }}"
    apply: true
  register: suite_sub_update

# TODO: Find a better way to know existing subscription is being upgraded
- name: "Pause for 2 minutes before checking MAS Core 8.7.x upgrade status..."
  pause:
    minutes: 2

# 1.2 Wait MAS 8.7.x to reconcile upgrade
# -----------------------------------------------------------------------------
- name: "Wait for Suite CR to finish reconciling upgrade to MAS 8.7.x successfully (60s delay)"
  kubernetes.core.k8s_info:
    api_version: v1
    name: "{{mas_instance_id}}"
    namespace: "{{mas_namespace}}"
    kind: Suite
  register: suite_cr_updated_result
  until:
    - suite_cr_updated_result.resources is defined
    - suite_cr_updated_result.resources | json_query('[*].status.conditions[?type==`Running`][].reason') | select ('match','Successful') | list | length == 1
    - suite_cr_updated_result.resources | json_query('[*].status.conditions[?type==`Failure`][].status') | select ('match','False') | list | length == 1
    - suite_cr_updated_result.resources | json_query('[*].status.conditions[?type==`Ready`][].reason') | select ('match','Ready') | list | length == 1
  retries: 60 # approx 60 minutes before we give up
  delay: 60 # 1 minute

# 1.3 Wait MAS 8.7.x to reconcile upgrade - Workspace CR
# -----------------------------------------------------------------------------
- name: "Wait for Suite Workspace CR to finish reconciling upgrade to MAS 8.7.x successfully (60s delay)"
  kubernetes.core.k8s_info:
    api_version: core.mas.ibm.com/v1
    kind: Workspace
    label_selectors:
      - mas.ibm.com/instanceId={{ mas_instance_id }}
  register: suite_ws_cr_updated_result
  until:
    - suite_ws_cr_updated_result.resources is defined
    - suite_ws_cr_updated_result.resources | json_query('[*].status.conditions[?type==`Running`][].reason') | select ('match','Successful') | list | length == 1
    - suite_ws_cr_updated_result.resources | json_query('[*].status.conditions[?type==`Failure`][].status') | select ('match','False') | list | length == 1
    - suite_ws_cr_updated_result.resources | json_query('[*].status.conditions[?type==`Ready`][].reason') | select ('match','Ready') | list | length == 1
  retries: 60 # approx 60 minutes before we give up
  delay: 60 # 1 minute

# 1.4 Restart SBO operator before we proceed with MAS apps upgrade
# Temporary workaround as sometimes SBO operators doesn't reconcile properly
# This will ensure the sbo secrets are up-to-date accross MAS apps prior its upgrade
# Will scale down and up again, as SBO pod doesn't have a good lookup matching label
# -----------------------------------------------------------------------------
- name: "Lookup SBO deployment"
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: service-binding-operator
    namespace: openshift-operators
  register: sbo_deployment

- name: "Scale down SBO operator before we proceed with MAS apps upgrade"
  when: sbo_deployment.resources | length > 0
  kubernetes.core.k8s:
    api_version: apps/v1
    kind: Deployment
    name: service-binding-operator
    namespace: openshift-operators
    definition:
      spec:
        replicas: 0
    apply: true

- name: "Scale up SBO operator before we proceed with MAS apps upgrade"
  when: sbo_deployment.resources | length > 0
  kubernetes.core.k8s:
    api_version: apps/v1
    kind: Deployment
    name: service-binding-operator
    namespace: openshift-operators
    definition:
      spec:
        replicas: 1
    apply: true

- name: "Wait SBO operator to be running again"
  when: sbo_deployment.resources | length > 0
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: service-binding-operator
    namespace: openshift-operators
  register: sbo_restart
  until:
    - sbo_restart.resources is defined
    - sbo_restart.resources[0].status is defined
    - sbo_restart.resources[0].status.readyReplicas is defined
    - sbo_restart.resources[0].status.readyReplicas == 1
  retries: 5 # approx 5 minutes before we give up
  delay: 60 # 1 minute

# 2. (optionally) Upgrade the application operators
# -----------------------------------------------------------------------------
# You don't need to upgrade the applications, you can leave them at the n-1
# supported versions from your previous MAS 8.6 installation if you wish.
- name: "Upgrade installed MAS applications to new feature releases in MAS 8.7"
  include_tasks: tasks/upgrade_mas_apps.yml
