---

# Provide intelligent storage class selection to minimize required user knowledge

# 1. Lookup storage class availabiity
# -----------------------------------------------------------------------------
- name: Lookup storage classes
  kubernetes.core.k8s_info:
    api_version: storage.k8s.io/v1
    kind: StorageClass
  register: lookup_storageclasses

- name: "Debug available storage classes"
  debug:
    msg: "{{ lookup_storageclasses | ibm.mas_devops.getResourceNames }}"

# 2. Set Storage (Required)
# -----------------------------------------------------------------------------
- name: Default Metadata Storage if not set by user
  when:
    - cpd_service_name != "wd"
    - cpd_service_storage_class is not defined or cpd_service_storage_class == ""
  vars:
    # ROKS, OCS, Azure
    supported_storage_classes: [ibmc-file-gold-gid, ocs-storagecluster-cephfs, azurefiles-premium]
  set_fact:
    cpd_service_storage_class: "{{ lookup_storageclasses | ibm.mas_devops.defaultStorageClass(supported_storage_classes) }}"

- name: Default Metadata Storage if not set by user (Watson Discovery only)
  when:
    - cpd_service_name == "wd"
    - cpd_service_storage_class is not defined or cpd_service_storage_class == ""
  vars:
    # ROKS, OCS, Azure
    supported_storage_classes: [ibmc-block-gold, ocs-storagecluster-ceph-rbd, managed-premium]
  set_fact:
    cpd_service_storage_class: "{{ lookup_storageclasses | ibm.mas_devops.defaultStorageClass(supported_storage_classes) }}"

- name: Assert that service storage class has been defined
  assert:
    that: cpd_service_storage_class is defined and cpd_service_storage_class != ""
    fail_msg: "cpd_service_storage_class must be defined"

# 3. Debug storage class configuration
# -----------------------------------------------------------------------------
- name: "Debug CP4D service {{ cpd_service_name }} storage class configuration"
  debug:
    msg:
      - "Storage class (CP4D service {{ cpd_service_name }}) ............................ {{ cpd_service_storage_class }}"
