---
# 1. Debug
# -----------------------------------------------------------------------------
- name: "Check that CPD Service name has been provided"
  assert:
    that: cpd_service_name is defined and cpd_service_name != ""
    fail_msg: "CPD service name (cpd_service_name) is a required parameter to run this role"

- debug:
    msg:
      - "CPD Product Version .................... {{ cpd_product_version }}"
      - "CPD Service ............................ {{ cpd_service_name }}"


# 2. Run the installation
# -----------------------------------------------------------------------------
- name: "Run install"
  include_tasks: "install.yml"
