---
cpd_version: "{{ lookup('env', 'CPD_VERSION') }}"
# As an alternative to using the cpd_version, the mas_channel can be used to dynamically determine the correct
# version of CPD to install (in some cases, but not all)
mas_channel: "{{ lookup('env', 'MAS_CHANNEL') }}"

cpd_registry: cp.icr.io
cpd_registry_user: cp

# This is only used for cpd35, we have to use cp4d_hack_worker_nodes to set up the global image pull secret needed by cpd40
cpd_entitlement_key: "{{ lookup('env', 'CPD_ENTITLEMENT_KEY') }}"

# Both CP4D storage classes have the same storage requirements as per recommendation from cpd support team
# so we set storageClass and zenCoreMetadbStorageClass to "{{ cpd_storage_class }}"
# https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=requirements-storage
#
# If this changes in the future we will expose a seperate variable for each.
cpd_storage_class: "{{ lookup('env', 'CPD_STORAGE_CLASS') }}"

# --- MAS channel control ---------------------------------------------------------------------------------------------
# Temporary solution: this will be used to determine whether to install CPD v4 or v3.5, if MAS channels from the below
# list are selected (older MAS releases still supporting CPD V3.5), then CPD v3.5 will be installed, otherwise CPD v4.0
# By default will we assume that we are installing for the main 8.x channel
mas_channels_old_releases: ['8.6.x', '8.5.x', 'maint86xdev']
cpd_supported_versions: ['cpd35', 'cpd40']
