---
# 4. Check installed applications are compatible with MAS 8.7
# -----------------------------------------------------------------------------
# 4.1 Assist
# Note: Assist is operating on an n-0 backwards compatability model in MAS 8.7,
# so there's no valid upgrade scenario as Assist 8.4 is not supported in earlier MAS releases either.
# In other words, you can't upgrade to MAS 8.7 if you have any prior version of Assist installed, sorry.
- name: "Check application compatability for Assist"
  include_tasks: tasks/app_version_check.yml
  vars:
    app_api_version: apps.mas.ibm.com/v1
    app_check_id: assist
    app_check_kind: AssistApp
    app_check_min_version: "8.4.0"
    app_check_max_version: "8.5.0"

# 4.1 HPUtils
- name: "Check application compatability for HPUtils"
  include_tasks: tasks/app_version_check.yml
  vars:
    app_api_version: apps.mas.ibm.com/v1
    app_check_id: hputilities
    app_check_kind: HPUtilitiesApp
    app_check_min_version: "8.2.0"
    app_check_max_version: "8.3.0"

# 4.3 IoT
- name: "Check application compatability for IoT"
  include_tasks: tasks/app_version_check.yml
  vars:
    app_api_version: iot.ibm.com/v1
    app_check_id: iot
    app_check_kind: IoT
    app_check_min_version: "8.4.0"
    app_check_max_version: "8.5.0"

# 4.4 Manage
- name: "Check application compatability for Manage"
  include_tasks: tasks/app_version_check.yml
  vars:
    app_api_version: apps.mas.ibm.com/v1
    app_check_id: manage
    app_check_kind: ManageApp
    app_check_min_version: "8.2.0"
    app_check_max_version: "8.3.0"

# 4.5 Monitor
- name: "Check application compatability for Monitor"
  include_tasks: tasks/app_version_check.yml
  vars:
    app_api_version: apps.mas.ibm.com/v1
    app_check_id: monitor
    app_check_kind: MonitorApp
    app_check_min_version: "8.6.0"
    app_check_max_version: "8.7.0"

# 4.6 Predict
- name: "Check application compatability for Predict"
  include_tasks: tasks/app_version_check.yml
  vars:
    app_api_version: apps.mas.ibm.com/v1
    app_check_id: predict
    app_check_kind: PredictApp
    app_check_min_version: "8.4.0"
    app_check_max_version: "8.5.0"

# 4.7 Safety
- name: "Check application compatability for Safety"
  include_tasks: tasks/app_version_check.yml
  vars:
    app_api_version: apps.mas.ibm.com/v1
    app_check_id: safety
    app_check_kind: Safety
    app_check_min_version: "8.2.0"
    app_check_max_version: "8.3.0"

# 4.8 Visual Inspection
# Note: Visual Inspection is operating on an n-0 backwards compatability model in MAS 8.7,
# so there's no valid upgrade scenario as MVI 8.5 is not supported in earlier MAS releases either.
# In other words, you can't upgrade to MAS 8.7 if you have any prior version of MVI installed, sorry.
- name: "Check application compatability for Visual Inspection"
  include_tasks: tasks/app_version_check.yml
  vars:
    app_api_version: apps.mas.ibm.com/v1
    app_check_id: visualinspection
    app_check_kind: VisualInspection
    app_check_min_version: "8.5.0"
    app_check_max_version: "8.6.0"
