---
# 3. Check the existing installation
# -----------------------------------------------------------------------------
# 3.1 Check the subscription
- name: "Get subscription channel of ibm-mas"
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    name: "ibm-mas-operator"
    namespace: "{{ mas_namespace }}"
    kind: Subscription
  register: suite_sub_info

- name: "Assert that the subscription for the suite core exists"
  assert:
    that:
      - suite_sub_info.resources is defined
      - suite_sub_info.resources | length == 1
    fail_msg: "Existing subscription for MAS Core in {{ mas_namespace }} could not be found"

- name: "Assert that the subscription for the suite is on a channel we can upgrade from"
  when: suite_sub_info.resources[0].spec.channel != mas_upgrade_target_channel
  assert:
    that:
      - suite_sub_info.resources[0].spec.channel is in mas_upgrade_supported_channels
    fail_msg: "Existing subscription for MAS Core ({{ suite_sub_info.resources[0].spec.channel }}) is not on a supported channel ({{ mas_upgrade_supported_channels }})"
    success_msg: "Existing MAS Core installation is in healthy state to upgrade to MAS 8.7.x!"

- name: "Assert that automatic upgrades are enabled as that is all we support atm"
  when: suite_sub_info.resources[0].spec.channel != mas_upgrade_target_channel
  assert:
    that:
      - suite_sub_info.resources[0].spec.installPlanApproval == 'Automatic'
    fail_msg: "Install plan approval for MAS Core subscription is not set to Automatic, this role does not support Manual upgrade approvals (yet)"

# 3.2 Check the CR
- name: "Get installed version of ibm-mas"
  kubernetes.core.k8s_info:
    api_version: core.mas.ibm.com/v1
    name: "{{ mas_instance_id }}"
    namespace: "{{ mas_namespace }}"
    kind: Suite
  register: suite_info

- name: "Assert that the core is installed"
  assert:
    that:
      - suite_info.resources is defined
      - suite_info.resources | length == 1
    fail_msg: "Existing MAS installation for {{ mas_instance_id }} could not be found"

- name: "Assert that the core is running a supported version to upgrade to MAS 8.7"
  when: suite_sub_info.resources[0].spec.channel != mas_upgrade_target_channel
  assert:
    that:
      - suite_info.resources[0].status.versions.reconciled is version('8.6.0', '>=')
      - suite_info.resources[0].status.versions.reconciled is version('8.7.0', '<')
    fail_msg: "Existing MAS installation is not running on MAS 8.6.x, so it cannot be upgraded to MAS 8.7.x"

- name: "Assert that the core is in healthy state to be upgrade to 8.7.x"
  assert:
    that:
      - suite_info.resources is defined
      - suite_info.resources | length == 1
      - suite_info.resources | json_query('[*].status.conditions[?type==`Running`][].reason') | select ('match','Successful') | list | length == 1
      - suite_info.resources | json_query('[*].status.conditions[?type==`Ready`][].reason') | select ('match','Ready') | list | length == 1
    fail_msg:
      - "Existing MAS installation for {{ mas_instance_id }} is not in ready state to be upgraded to MAS 8.7.x, check its CR status for more details!"
