---
# 1. Check for undefined properties that do not have a default
# -----------------------------------------------------------------------------
- name: "Assert that mas_instance_id is defined"
  assert:
    that:
      - mas_instance_id is defined
      - mas_instance_id != ""
    fail_msg: "mas_instance_id property is required"

# 2. Provide debug information
# -----------------------------------------------------------------------------
- name: "Debug information"
  debug:
    msg:
      - "Catalog source ............... {{ mas_catalog_source }}"
      - "Instance ID .................. {{ mas_instance_id }}"
      - "MAS namespace ................ {{ mas_namespace }}"

# 3. Check the existing installation
# -----------------------------------------------------------------------------
- name: "Check existing MAS installation"
  include_tasks: tasks/check_mas_install.yml

# 4. Check installed applications are compatible with MAS 8.7
# -----------------------------------------------------------------------------
- name: "Check installed MAS application compatability with MAS 8.7"
  include_tasks: tasks/check_mas_apps.yml
