---
# TODO: Instead of a dummy pause, find a better way to identify whether the patched subscriptions are reconciling the upgrade
# we can't simply check for Apps CR status = Successful because the ansible script sometimes is
# quicker to check for the Successful condition and will meet the condition earlier while apps are still in MAS 8.6.x level
# even before the Apps CR starts reconciling the upgrade...
# For now, the 2 minute warning is doing the trick, after this pause we'll expect the MAS Apps to be reconciling the 8.7.x upgrade
# And the following tasks will check and wait until all MAS Apps CR / Workspace CRs to successfully reconcile the upgrade
- name: "Pause for 2 minutes before checking MAS applications upgrade status..."
  pause:
    minutes: 2

# Wait all apps to complete upgrade
- name: Wait MAS apps to complete upgrade to 8.7 version
  include_tasks: tasks/wait/wait_for_app_upgrade.yml

# After apps upgraded, wait for all apps workspace operators to reconcile
- name: 'Wait MAS apps workspace operators to reconcile the upgrade'
  include_tasks: tasks/wait/wait_for_app_ws_upgrade.yml

- debug:
    msg: "MAS Applications {{ mas_apps }} successfully upgraded to MAS 8.7 version!"
