---
# MAS configuration
mas_instance_id: "{{ lookup('env', 'MAS_INSTANCE_ID') }}"
mas_workspace_id: "{{ lookup('env', 'MAS_WORKSPACE_ID') }}"

# MAS application configuration
mas_app_id: "{{ lookup('env', 'MAS_APP_ID') }}"
mas_appws_jdbc_binding: "{{ lookup('env', 'MAS_APPWS_JDBC_BINDING') }}"
mas_appws_components: "{{ lookup('env', 'MAS_APPWS_COMPONENTS') | ibm.mas_devops.appws_components | default('{}', true) }}"

# Specifically for Manage application configuration
# We want to avoid application specifics, hopefully we can remove this and find a better way
db2_schema: "{{ lookup('env', 'MAS_DB2_SCHEMA') | default('maximo', true)}}"
manage_demo_data: "{{ lookup('env', 'MAS_DB_IMPORT_DEMO_DATA') | default('false', true) }}"
aio_flag: "{{ lookup('env', 'MANAGE_AIO_FLAG') | default('false', true)}}"
