name: Publish Tekton Defintion
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '**'
jobs:
  tekton-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Initialise the build system
        run: |
          chmod u+x $GITHUB_WORKSPACE/build/bin/*.sh
          $GITHUB_WORKSPACE/build/bin/initbuild.sh
          source $GITHUB_WORKSPACE/build/bin/.functions.sh
          python -m pip install -q ansible==2.10.3 yamllint

      - name: Initialise the build system
        run: |
          chmod u+x $GITHUB_WORKSPACE/build/bin/*.sh
          $GITHUB_WORKSPACE/build/bin/initbuild.sh
          source $GITHUB_WORKSPACE/build/bin/.functions.sh

      - name: Build the ClusterTasks definition file
        run: $GITHUB_WORKSPACE/pipelines/bin/build-pipelines.sh

      - name: Upload Tekton Definitions
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/pipelines/ibm-mas-devops-tasks-${{ env.VERSION }}.yaml
          asset_name: ibm-mas-devops-tasks-${{ env.VERSION }}.yaml
          tag: ${{ github.ref }}
          overwrite: true
